apiVersion: v1
kind: Service
metadata:
  name: poc-teste-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: poc-teste
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-teste-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-teste
  template:
    metadata:
      labels:
        app: poc-teste
    spec:
      containers:
        - name: poc-teste
          image: gcr.io/google-samples/kubernetes-bootcamp:v1
          ports:
            - containerPort: 8080