apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: poc-teste
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/jospin/testkube.git
   targetRevision: HEAD
   path: postman-collections
   plugin:
     name: "testkube-v1.0"
 destination:
   server: https://kubernetes.default.svc
   namespace: testkube